#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set luci.main.lang=zh_cn
	set system.@system[0].hostname=Mediatek_AP
	set system.@system[0].timezone=CST-8
	set system.@system[0].zonename=Asia/Shanghai
	set fstab.@global[0].anon_mount=1
	set wireless.@wifi-device[0].disabled=0
	set wireless.@wifi-device[1].disabled=0
	set wireless.@wifi-iface[0].wpa_disable_eapol_key_retries='1'
	set wireless.@wifi-iface[1].wpa_disable_eapol_key_retries='1'
	set wireless.radio0.country='US'
	set wireless.radio1.country='US'
	set dropbear.@dropbear[0].Interface='lan'
	set wireless.@wifi-iface[0].ssid=Lunatic_2.4G_$(cat /sys/class/ieee80211/phy0/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
	set wireless.@wifi-iface[1].ssid=Lunatic_5G_$(cat /sys/class/ieee80211/phy1/macaddress | sed 's/.[0-9A-Fa-f]:.[0-9A-Fa-f]:.[0-9A-Fa-f]:\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\):\(.[0-9A-Fa-f]\)/\1\2\3/g' | tr :[a-z] :[A-Z])
	set network.lan.ipaddr=192.168.66.1
	set wireless.radio0.legacy_rates='0'
	set wireless.radio1.legacy_rates='0'
	set wireless.@wifi-iface[0].disassoc_low_ack='1'
	set wireless.@wifi-iface[0].short_preamble='1'
	set wireless.@wifi-iface[1].short_preamble='1'
	set wireless.@wifi-iface[1].disassoc_low_ack='1'
	set wireless.@wifi-iface[0].ieee80211k='1'
	set wireless.@wifi-iface[0].ieee80211v='1'
	set wireless.@wifi-iface[0].time_advertisement='0'
	set wireless.@wifi-iface[1].ieee80211k='1'
	set wireless.@wifi-iface[1].ieee80211v='1'
	set wireless.@wifi-iface[1].time_advertisement='0'
	add_list umdns.@umdns[0].network='wan'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	del_list uhttpd.main.listen_https='0.0.0.0:443'
	del_list uhttpd.main.listen_https='[::]:443'
	set luci.main.mediaurlbase='/luci-static/argon'
	set firewall.@zone[1].input='ACCEPT'
	commit
EOF

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release


/etc/init.d/qos_gargoyle disable
# /etc/init.d/umdns stop
# /etc/init.d/umdns disable
# /etc/init.d/dawn stop
# /etc/init.d/dawn disable
/etc/init.d/https-dns-proxy stop
/etc/init.d/https-dns-proxy disable
/etc/init.d/advancedplus stop
/etc/init.d/advancedplus disable
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/openwrt#g' /etc/opkg/distfeeds.conf










exit 0
